### ISSUE TITLE
Bug: Error en copia de correo de docentes

### ISSUE THREAD

**Issue by JoseFer2001** [imlargo/salidas-campo#26]
**Describe the bug**
Al momento de dirigirse al panel de vicedecanatura y hacer la carga de la lista de proyectados, cuando se pasa el cursor por encima del nombre del docente, este en teoria permite copiar el correo del docente, en lugar de esto, solo copia el link del formulario de proyección https://salidas-campo.vercel.app/form/proyeccion

**Screenshots**
![image](https://github.com/user-attachments/assets/3cf9f784-df79-4fde-bbc0-1a2f4241cffa)

**Additional context**
Se puede hacer lo siguiente:

1. Eliminar esta función
2. Arreglarla

Esto teniendo en cuenta que no es un requisito vital del sistema.

**Comment by imlargo** [comment]
arreglado
